ethereum-oasis-op/oasis-open-project

meetings/2020-04-20.md
meetings/2020-05-04.md

Meeting minutes from April 20 & May 4

add meeting minutes from last two meetings

---

GOVERNANCE.md

Per today's PGB meeting, here are the changes we worked on in our session

Update Governance.md per PGB Meeting

---

meetings/2020-08-12.md

meeting minutes from last week.

add meeting minutes for 12 August meeting

---

README.md

Change Nethermind PGB Rep

---

PROJECT-GOVERNING-BOARD.md
README.md

Changes for transition

---

meetings/2022-02-10-DRAFT.md

Added one item missing from the minutes.
Other minor cleanup.

Finish and clean up 10 Feb 2022 minutes

---

meetings/2021-02-10.md

Adds meeting minutes for PGB meeting, 2021-02-10

---

meetings/2021-02-24.md

Adds minutes for PGB call on 2021-02-24

---

meetings/2021-03-10.md

Adds minutes for meeting on 10 March 2021

---

2021-03-24.md

Adds meetings minutes for 24 March 2021

---

meetings/2021-04-07.md

Adds minutes for 7 April 2021

---

meetings/2021-04-21.md

Adds meeting minutes from 21 April 2021

---

meetings/2021-05-05.md

Adds minutes for meeting on 5 May 2021

---

meetings/2021-05-19.md

Adds PGB meeting minutes for 19 May 2021

---

meetings/2021-06-02.md

Adds PGB meeting minutes for meeting on 2 June 2021

---

meetings/2021-06-16.md

Adds meeting minutes for 16 June meeting

---

meetings/2021-06-30.md

creates minutes for PGB meeting on 30 June

---

meetings/2021-07-14.md

Adds file for minutes for PGB meeting on 14 July

---

meetings/2021-07-28.md

Creates minutes for PGB meeting on 28 July 2021

---

meetings/2021-08-11.md

Creates meeting minutes for 11 August meeting

---

meetings/2021-08-25.md

creates meeting minutes for 25 August

---

meetings/2021-09-08.md

draft of PGB meeting minutes for 8 September

---

meetings/2021-09-22.md

creates draft of meeting minutes for 22 September

---

meetings/2021-10-20.md

Adds minutes for 20 October meeting

---

meetings/2021-11-03.md

Creates minutes for 3 November 2021 meeting

---

meetings/2021-11-17.md

Adds minutes for 17 November meeting

---

meetings/2021-12-01.md

Adds minutes for 1 December 2021 meeting

---

meetings/2021-12-16.md

creates minutes for 16 Dec 2021 meeting

---

meetings/2022-05-05.md

Update 5 May 2022 minutes

---

GOVERNANCE.md

To be merged if #63 is approved by the PGB.

Add reference to STANDING-RULES.md per PR #63

---

CODE-OF-CONDUCT.md

As a first step to adding more details to our code of conduct, I suggest updating from 1.4 to 2.1 of the [Contributor Covenant](https://www.contributor-covenant.org/)
Signed-off-by: Tracy Kuhrt <tracy.a.kuhrt@accenture.com>

Update to version 2.1 from 1.4

---

GOVERNANCE.md

...instead of a special majority vote

TSC chairs can be appointed by a simple majority vote 

---

GOVERNANCE.md

Adds TokenScript to Code Respositories section

Adds Tokenscript
